require("OOP.Class")
require("OOP.ClassGCHandle")
require("Util.TableUtil")
require("Util.Util")
require("Core.Interface.ILifeCycle")
require("Core.Interface.IFixedUpdate")
require("Core.Interface.IUpdate")
require("Core.Interface.ILateUpdate")
require("Core.Interface.IComponent")
require("Core.Interface.IEntity")
require("Core.Mgr.GenerateIdMgr")
require("Core.Mgr.UpdateMgr")
require("Core.Abs.AbsComponent.AbsComponent")
require("Core.Abs.AbsEntity.AbsEntity")
require("Core.Abs.AbsMgr.AbsEntityMgr")
require("Core.Abs.AbsBehaviour.AbsBehaviour")
require("Module.Battle.Component.LookAtComponent")
require("Module.Battle.Entity.SimpleFishEntity")
require("Module.Battle.Mgr.BattleEntityMgr")
require("Module.Battle.Behaviour.BattleBehaviour")


